<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>input[id=&quot;form_receiver&quot;]</description>
   <name>FieldReceiver</name>
   <tag></tag>
   <elementGuidId>7b37823d-366e-454c-9841-4d94bd5c4d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_receiver</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
