<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>/html/body/div[2]/div[2]/button[29]</description>
   <name>KeyBoard_A</name>
   <tag></tag>
   <elementGuidId>2763a08b-a203-47c5-992e-73ab46c7313c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[2]/button[29]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
